// SPDX-License-Identifier: MPL-2.0
//! Export round trip over IFC files **authored by other tools**.
//!
//! Every other round-trip test in this repo writes a file with this crate's
//! writer and reads it back with this crate's reader. That shape is blind to
//! three failures at once: a field neither side handles, a field both sides get
//! wrong the same way, and — the common one — a field no hand-written fixture
//! ever populates. `parse(write(x)) == x` holds in all three.
//!
//! The corpus fetched by `pnpm fixtures` is the only interop evidence available
//! that was not produced here: real exports from unrelated authoring pipelines,
//! carrying constructs no fixture in this repo would have thought to write. This
//! module reads one of those files, writes it back through [`export_step`],
//! reads the result, and compares the two semantic snapshots.
//!
//! ## What the comparison asserts
//!
//! 1. **Entity census** — the count of every IFC type, before and after. A type
//!    the scanner drops (an unusual line shape, an escape it mis-terminates)
//!    moves a count.
//! 2. **The full extracted model** — [`ExportModel`] with placements, declared
//!    attributes and type-inherited property sets all switched on. That is every
//!    product's express id, GlobalId, Name, Description, ObjectType, geometry
//!    flag, resolved placement, property sets, quantity sets and declared
//!    attributes, plus the project's unit scales.
//! 3. **Georeference** — the `IfcMapConversion`/`IfcProjectedCRS` payload,
//!    including the map unit and its scale, compared field-for-field.
//! 4. **Coordinate extent** — the bounding box over every `IfcCartesianPoint`,
//!    bit-exact, and the number of points it was taken over.
//! 5. **Schema label** — the `FILE_SCHEMA` the writer emits must be the one it
//!    read, since the writer preserves it unless asked to convert.
//!
//! ## What it does NOT assert
//!
//! - **Byte equality.** The header is regenerated by design, so the files
//!   differ, and nothing here compares raw text.
//! - **Geometry as geometry.** Nothing is tessellated. A representation is
//!   covered only by its entity-type census, its product's `has_geometry` flag
//!   and the coordinate extent above; a defect that permuted the vertices of a
//!   face while preserving every count and the bounding box would pass.
//! - **Header metadata.** FILE_DESCRIPTION, FILE_NAME, author, organisation and
//!   timestamp are deliberately replaced by the writer, so their loss is by
//!   design and not something a round trip can be asked to catch.
//! - **Non-product entities' attributes.** [`ExportModel`] rows are products and
//!   orphan-geometry type products. A materials/library/constraint entity is
//!   covered by the census (it is still counted) but not attribute-by-attribute.
//! - **Express-id renumbering.** The writer preserves ids on a full export, so
//!   the comparison is keyed on them. A writer that renumbered would fail here
//!   even if it renumbered consistently — a deliberate choice, not an oversight:
//!   renumbering a full export is not a behaviour anything asks for.
//!
//! ## Why these files
//!
//! Six files, six unrelated authoring pipelines, three schema generations
//! (IFC2X3, IFC4, IFC4X3), covering an architectural model, a structural model,
//! an MEP model and an infrastructure model. Two carry a real georeference;
//! several carry element quantities; one is a schema generation with no
//! dedicated handling in the writer. Breadth over depth was rejected on
//! purpose: 300 files compared shallowly would report a bigger number and catch
//! less.
//!
//! ## Absence is a failure, not a skip
//!
//! `fixture_or_skip!` skips when the corpus has not been fetched, and panics
//! when `IFC_LITE_REQUIRE_FIXTURES=1` — which CI sets. A file that vanishes from
//! the manifest therefore turns this suite red rather than quietly shrinking it.

use super::*;
use ifc_lite_core::scan_model_bounds;
use ifc_lite_processing::{extract_georeferencing, Georeferencing};
use std::collections::{BTreeMap, HashSet};

use crate::{build_export_model_with_options, EntityRow, ExportModel, ModelOptions};

/// Everything the round trip compares, derived from one file's bytes.
struct Snapshot {
    schema: String,
    census: BTreeMap<String, usize>,
    model: ExportModel,
    georef: Option<Georeferencing>,
    bounds: (f64, f64, f64, f64, f64, f64, usize),
}

fn snapshot(content: &[u8]) -> Snapshot {
    let mut census: BTreeMap<String, usize> = BTreeMap::new();
    let mut scanner = EntityScanner::new(content);
    while let Some((_id, type_name, _s, _e)) = scanner.next_entity() {
        *census.entry(type_name.to_ascii_uppercase()).or_insert(0) += 1;
    }

    let opts = ModelOptions::default()
        .with_placements(true)
        .with_inherit_type_properties(true)
        .with_attributes(true);
    let mut model = build_export_model_with_options(content, &opts);
    // Keyed on express id rather than on emission order: the index behind the
    // model is built in parallel, and pinning an order this test does not care
    // about would make it flake on a scheduling difference rather than on a
    // defect.
    model.entities.sort_by_key(|r| r.express_id);

    let b = scan_model_bounds(content);

    Snapshot {
        schema: crate::step_text::detect_schema(content),
        census,
        model,
        georef: extract_georeferencing(content),
        bounds: (b.min_x, b.min_y, b.min_z, b.max_x, b.max_y, b.max_z, b.sample_count),
    }
}

/// The first semantic difference between two snapshots, or `None`.
///
/// A `String` rather than an `assert_eq!` on the whole structure deliberately:
/// these models run to tens of thousands of rows, and a failure that dumps both
/// of them is a failure nobody can read. It also makes the comparison itself
/// testable — [`a_changed_global_id_is_caught`] and its neighbours assert that
/// specific perturbations produce `Some`.
fn first_difference(before: &Snapshot, after: &Snapshot) -> Option<String> {
    if before.schema != after.schema {
        return Some(format!(
            "FILE_SCHEMA changed: {} -> {}",
            before.schema, after.schema
        ));
    }

    for (ty, n) in &before.census {
        let m = after.census.get(ty).copied().unwrap_or(0);
        if m != *n {
            return Some(format!("entity count for {ty}: {n} -> {m}"));
        }
    }
    for ty in after.census.keys() {
        if !before.census.contains_key(ty) {
            return Some(format!("entity type {ty} appeared in the output"));
        }
    }

    if before.model.units != after.model.units {
        return Some(format!(
            "project units changed: {:?} -> {:?}",
            before.model.units, after.model.units
        ));
    }

    if before.model.entities.len() != after.model.entities.len() {
        return Some(format!(
            "model row count: {} -> {}",
            before.model.entities.len(),
            after.model.entities.len()
        ));
    }
    for (b, a) in before.model.entities.iter().zip(&after.model.entities) {
        if b != a {
            return Some(row_difference(b, a));
        }
    }

    if before.georef != after.georef {
        return Some(format!(
            "georeference changed: {:?} -> {:?}",
            before.georef, after.georef
        ));
    }

    if before.bounds != after.bounds {
        return Some(format!(
            "coordinate extent changed: {:?} -> {:?}",
            before.bounds, after.bounds
        ));
    }

    None
}

/// Name the field that differs, so a failure points at one attribute instead of
/// printing two whole rows and leaving the reader to diff them by eye.
fn row_difference(b: &EntityRow, a: &EntityRow) -> String {
    let head = format!("#{} ({})", b.express_id, b.ifc_type);
    if b.express_id != a.express_id {
        return format!("express id {} -> {}", b.express_id, a.express_id);
    }
    if b.ifc_type != a.ifc_type {
        return format!("{head}: type -> {}", a.ifc_type);
    }
    for (field, x, y) in [
        ("GlobalId", &b.global_id, &a.global_id),
        ("Name", &b.name, &a.name),
        ("Description", &b.description, &a.description),
        ("ObjectType", &b.object_type, &a.object_type),
    ] {
        if x != y {
            return format!("{head}: {field} {x:?} -> {y:?}");
        }
    }
    if b.has_geometry != a.has_geometry {
        return format!(
            "{head}: has_geometry {} -> {}",
            b.has_geometry, a.has_geometry
        );
    }
    if b.placement != a.placement {
        return format!("{head}: placement {:?} -> {:?}", b.placement, a.placement);
    }
    if b.property_sets != a.property_sets {
        return format!(
            "{head}: property sets {:?} -> {:?}",
            b.property_sets, a.property_sets
        );
    }
    if b.quantity_sets != a.quantity_sets {
        return format!(
            "{head}: quantity sets {:?} -> {:?}",
            b.quantity_sets, a.quantity_sets
        );
    }
    if b.attributes != a.attributes {
        return format!(
            "{head}: attributes {:?} -> {:?}",
            b.attributes, a.attributes
        );
    }
    format!("{head}: rows differ")
}

/// Write `content` back out with the default options and compare snapshots.
fn assert_round_trip(label: &str, content: &[u8]) {
    let before = snapshot(content);
    // A snapshot that saw nothing would make every comparison below vacuous.
    assert!(
        before.model.entities.len() > 1,
        "{label}: the source parses to {} model rows — this file cannot evidence anything",
        before.model.entities.len()
    );

    let written = export_step(content, &StepOptions::default());
    let after = snapshot(written.as_bytes());

    if let Some(diff) = first_difference(&before, &after) {
        panic!("{label}: round trip lost semantic content — {diff}");
    }
}

// ── The corpus ──────────────────────────────────────────────────────────────

/// IFC4 from a SketchUp-based exporter. Carries an `IfcMapConversion` and an
/// `IfcProjectedCRS`, so this file (with the infrastructure one below) is what
/// puts the georeference comparison on real authored data rather than on a
/// fixture written to exercise it.
#[test]
fn architectural_sketchup_ifc4() {
    assert_round_trip(
        "buildingsmart/Building-Architecture.ifc",
        &fixture_or_skip!("buildingsmart/Building-Architecture.ifc"),
    );
}

/// IFC4X3_RC4 from an infrastructure design tool — a schema generation and a
/// domain (alignment, linear placement) nothing else in this module covers, and
/// a second real georeference.
#[test]
fn infrastructure_ifc4x3() {
    assert_round_trip("AB22.ifc", &fixture_or_skip!("AB22.ifc"));
}

/// IFC2X3 from a widely used architectural authoring tool, ~1.5k property sets.
/// The property-set half of the comparison is mostly carried by this file.
#[test]
fn architectural_ifc2x3_with_many_property_sets() {
    assert_round_trip("ara3d/duplex.ifc", &fixture_or_skip!("ara3d/duplex.ifc"));
}

/// IFC4 written through a different STEP toolkit again, with both property sets
/// and element quantities, and header strings carrying backslash escapes — the
/// case a naive line scanner terminates early on.
#[test]
fn architectural_ifc4_with_quantities() {
    assert_round_trip(
        "ara3d/AC20-FZK-Haus.ifc",
        &fixture_or_skip!("ara3d/AC20-FZK-Haus.ifc"),
    );
}

/// IFC4 MEP — duct fittings, a discipline whose representations differ from
/// every architectural file above.
#[test]
fn mep_ifc4() {
    assert_round_trip(
        "ifcopenshell/1269--Project_IfcDuctFitting.ifc",
        &fixture_or_skip!("ifcopenshell/1269--Project_IfcDuctFitting.ifc"),
    );
}

/// IFC2X3 structural, passed through a third-party optimizer before it reached
/// us — so its entity layout is not what its original authoring tool emitted,
/// and it is dense in element quantities.
#[test]
fn structural_ifc2x3_optimized() {
    assert_round_trip(
        "various/02_BIMcollab_Example_STR_random_C_ebkp.ifc",
        &fixture_or_skip!("various/02_BIMcollab_Example_STR_random_C_ebkp.ifc"),
    );
}

// ── Proof the comparison can fail ───────────────────────────────────────────
//
// A round trip that cannot fail is the same defect one level up, and this one
// runs against a writer that copies most entity lines through verbatim — the
// configuration in which a vacuous pass is easiest to mistake for a real one.
// Each test below perturbs the WRITER's output, through options the writer
// already supports, and asserts a specific facet of `first_difference` reports
// it. They are the reason a green run above means something.

/// Identity: change one product's GlobalId on the way out.
#[test]
fn a_changed_global_id_is_caught() {
    let content = fixture_or_skip!("ifcopenshell/1269--Project_IfcDuctFitting.ifc");
    let before = snapshot(&content);
    let victim = before
        .model
        .entities
        .iter()
        .find(|r| r.global_id.is_some())
        .expect("the file must have at least one product with a GlobalId");

    let written = export_step(
        &content,
        &StepOptions {
            attribute_mutations: vec![AttrMutation {
                express_id: victim.express_id,
                index: 0,
                value: "'0zzzzzzzzzzzzzzzzzzzzz'".to_string(),
            }],
            ..StepOptions::default()
        },
    );
    let diff = first_difference(&before, &snapshot(written.as_bytes()))
        .expect("a rewritten GlobalId must be caught");
    assert!(
        diff.contains("GlobalId"),
        "the difference must name the GlobalId, got: {diff}"
    );
}

/// Content: add a property set the source never had.
#[test]
fn an_added_property_set_is_caught() {
    let content = fixture_or_skip!("ifcopenshell/1269--Project_IfcDuctFitting.ifc");
    let before = snapshot(&content);
    let victim = before
        .model
        .entities
        .iter()
        .find(|r| r.global_id.is_some())
        .expect("the file must have at least one product with a GlobalId");

    let written = export_step(
        &content,
        &StepOptions {
            property_mutations: vec![PropMutation {
                express_id: victim.express_id,
                pset_name: "Pset_NotInTheSource".to_string(),
                prop_name: "Invented".to_string(),
                value: "IFCLABEL('x')".to_string(),
            }],
            ..StepOptions::default()
        },
    );
    assert!(
        first_difference(&before, &snapshot(written.as_bytes())).is_some(),
        "a property set that is not in the source must be caught"
    );
}

/// Georeference: move the map conversion's false easting by one metre.
///
/// This is the facet a self-round-trip could never have exercised, because no
/// fixture written here would have carried an authored `IfcMapConversion` in
/// the first place. `Eastings` is attribute index 2 of `IfcMapConversion`
/// (SourceCRS, TargetCRS, Eastings, …).
#[test]
fn a_moved_georeference_is_caught() {
    let content = fixture_or_skip!("buildingsmart/Building-Architecture.ifc");
    let before = snapshot(&content);
    let eastings = before
        .georef
        .as_ref()
        .expect(
            "this file is in the set BECAUSE it is georeferenced; if that stopped \
             being true the georeference comparison above would be running on nothing",
        )
        .eastings;

    let mut scanner = EntityScanner::new(&content);
    let mut map_conversion = None;
    while let Some((id, type_name, _s, _e)) = scanner.next_entity() {
        if type_name.eq_ignore_ascii_case("IFCMAPCONVERSION") {
            map_conversion = Some(id);
            break;
        }
    }
    let map_conversion = map_conversion.expect("georeferenced file must hold an IfcMapConversion");

    let moved = eastings + 1.0;
    let written = export_step(
        &content,
        &StepOptions {
            attribute_mutations: vec![AttrMutation {
                express_id: map_conversion,
                index: 2,
                value: format!("{moved:?}"),
            }],
            ..StepOptions::default()
        },
    );
    let diff = first_difference(&before, &snapshot(written.as_bytes()))
        .expect("a moved false easting must be caught");
    assert!(
        diff.contains("georeference"),
        "the difference must name the georeference, got: {diff}"
    );
}

/// Structure: drop an entity the source had.
///
/// Exported as a subset that excludes one record, which is the closest the
/// writer's own options come to the failure the census exists to catch — a
/// record the scanner silently fails to re-emit. An
/// `IfcRelDefinesByProperties` is chosen because nothing references one, so the
/// forward closure cannot pull it back in.
#[test]
fn a_dropped_entity_is_caught() {
    let content = fixture_or_skip!("ifcopenshell/1269--Project_IfcDuctFitting.ifc");
    let before = snapshot(&content);

    let mut scanner = EntityScanner::new(&content);
    let mut keep = Vec::new();
    let mut dropped = None;
    while let Some((id, type_name, _s, _e)) = scanner.next_entity() {
        if dropped.is_none() && type_name.eq_ignore_ascii_case("IFCRELDEFINESBYPROPERTIES") {
            dropped = Some(id);
            continue;
        }
        keep.push(id);
    }
    assert!(
        dropped.is_some(),
        "file must hold an IfcRelDefinesByProperties"
    );

    let written = export_step(
        &content,
        &StepOptions {
            included: Some(keep),
            ..StepOptions::default()
        },
    );
    let diff = first_difference(&before, &snapshot(written.as_bytes()))
        .expect("an entity missing from the output must be caught");
    assert!(
        diff.contains("IFCRELDEFINESBYPROPERTIES") || diff.contains("property sets"),
        "the difference must name the dropped record or the properties it \
         carried, got: {diff}"
    );
}

// ── Subset export over third-party input ────────────────────────────────────

/// A filtered export of a third-party file must not dangle a reference.
///
/// The reference closure is the one part of the writer that is not a
/// passthrough, and it has only ever been exercised on files written here. A
/// real file references through constructs a hand-written fixture does not use
/// — mapped items, presentation layer assignments, styled item chains — and
/// every one of them has to be pulled in or the output is unreadable.
#[test]
fn subset_export_of_third_party_products_dangles_no_reference() {
    let content = fixture_or_skip!("ara3d/AC20-FZK-Haus.ifc");

    let mut total = 0usize;
    let mut roots = Vec::new();
    let mut scanner = EntityScanner::new(&content);
    while let Some((id, type_name, _s, _e)) = scanner.next_entity() {
        total += 1;
        if type_name.eq_ignore_ascii_case("IFCWALLSTANDARDCASE")
            || type_name.eq_ignore_ascii_case("IFCWALL")
        {
            roots.push(id);
        }
    }
    assert!(
        !roots.is_empty(),
        "the file must hold walls, or this test filters on nothing"
    );

    let written = export_step(
        &content,
        &StepOptions {
            included: Some(roots.clone()),
            ..StepOptions::default()
        },
    );

    let out_bytes = written.as_bytes();
    let mut present: HashSet<u32> = HashSet::new();
    let mut lines: Vec<(u32, usize, usize)> = Vec::new();
    let mut out_scanner = EntityScanner::new(out_bytes);
    while let Some((id, _t, s, e)) = out_scanner.next_entity() {
        present.insert(id);
        lines.push((id, s, e));
    }

    assert!(
        present.len() < total,
        "a subset that emitted all {total} entities proves nothing about the closure"
    );
    for root in &roots {
        assert!(
            present.contains(root),
            "#{root} was asked for but is not in the subset"
        );
    }

    let mut refs = Vec::new();
    for (id, s, e) in &lines {
        refs.clear();
        crate::step_text::refs_in_line(&out_bytes[*s..*e], &mut refs);
        for r in &refs {
            assert!(
                present.contains(r),
                "#{id} in the subset references #{r}, which the closure did not emit"
            );
        }
    }
}
